### ISSUE TITLE
After install, get error for missing module

### ISSUE THREAD

**Issue by lorezyra** [quocvu/hexo-tag-youtube-responsive#3]
Installed this plugin and ran ```hexo server```. I see the following output:

```
 $ hexo server
INFO  Validating config
ERROR {
  err: Error: Cannot find module 'filename-regex'
  Require stack:
  - /Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/micromatch/lib/utils.js
  - /Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/micromatch/lib/expand.js
  - /Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/micromatch/index.js
  - /Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/anymatch/index.js
  - /Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/chokidar/index.js
  - /Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/hexo-fs/lib/fs.js
  - /Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/lib/logic.js
  - /Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/index.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
      at Function.Module._load (node:internal/modules/cjs/loader:769:27)
      at Module.require (node:internal/modules/cjs/loader:996:19)
      at require (node:internal/modules/cjs/helpers:92:18)
      at Object.<anonymous> (/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/micromatch/lib/utils.js:5:14)
      at Module._compile (node:internal/modules/cjs/loader:1092:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
      at Module.load (node:internal/modules/cjs/loader:972:32)
      at Function.Module._load (node:internal/modules/cjs/loader:813:14)
      at Module.require (node:internal/modules/cjs/loader:996:19)
      at require (node:internal/modules/cjs/helpers:92:18)
      at Object.<anonymous> (/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/micromatch/lib/expand.js:10:13)
      at Module._compile (node:internal/modules/cjs/loader:1092:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
      at Module.load (node:internal/modules/cjs/loader:972:32)
      at Function.Module._load (node:internal/modules/cjs/loader:813:14)
      at Module.require (node:internal/modules/cjs/loader:996:19)
      at require (node:internal/modules/cjs/helpers:92:18)
      at Object.<anonymous> (/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/micromatch/index.js:10:14)
      at Module._compile (node:internal/modules/cjs/loader:1092:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
      at Module.load (node:internal/modules/cjs/loader:972:32) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/micromatch/lib/utils.js',
      '/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/micromatch/lib/expand.js',
      '/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/micromatch/index.js',
      '/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/anymatch/index.js',
      '/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/chokidar/index.js',
      '/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/node_modules/hexo-fs/lib/fs.js',
      '/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/lib/logic.js',
      '/Users/lorezyra/Documents/blog.RichieBartlett.com/node_modules/hexo-auto-category/index.js'
    ]
  }
} Plugin load failed: %s hexo-auto-category
INFO  Start processing
===== undefined -----
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
```

Server starts and I can see the video is rendered with full width, but still it is failing to find ```module 'filename-regex'```.

**Comment by lorezyra** [comment]
Sorry, wrong github project.
